/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const HerosIndexLazyImport = createFileRoute('/heros/')()
const HerosIdLazyImport = createFileRoute('/heros/$id')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const HerosIndexLazyRoute = HerosIndexLazyImport.update({
  path: '/heros/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/heros/index.lazy').then((d) => d.Route))

const HerosIdLazyRoute = HerosIdLazyImport.update({
  path: '/heros/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/heros/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/heros/$id': {
      preLoaderRoute: typeof HerosIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/heros/': {
      preLoaderRoute: typeof HerosIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  HerosIdLazyRoute,
  HerosIndexLazyRoute,
])

/* prettier-ignore-end */
